name       : bup
version    : 0.29.2
release    : 2
source     :
    - https://github.com/bup/bup/archive/0.29.2.tar.gz : 7f54503f305eab5db5db41e1825477b8804870ca251f65bcfb4d89ad2598574f
license    :
    - BSD-2-Clause
    - LGPL-2.0-or-later
    - Python-2.0
component  : system.util
summary    : Efficient backup system based on git
description: |
    Very efficient backup system based on the git packfile format, providing fast incremental saves and global deduplication (among and within files, including virtual machine images).
builddeps  :
    - git
    - par2cmdline       # check
    - python-pyxattr    # check
    - python-pylibacl   # check
    - python-tornado    # check
    - rsync             # check
rundeps    :
    - git
    - par2cmdline
    - python-pyxattr
    - python-pylibacl
build      : |
    %make
install    : |
    %make_install PREFIX=%PREFIX% LIBDIR=%libdir%/bup
check      : |
    %make check
