name       : bup
version    : '0.32'
release    : 8
source     :
    - https://github.com/bup/bup/archive/0.32.tar.gz : a894cfa96c44b9ef48003b2c2104dc5fa6361dd2f4d519261a93178984a51259
homepage   : https://bup.github.io
license    :
    - BSD-2-Clause
    - LGPL-2.0-or-later
    - Python-2.0
component  : system.utils
summary    : Efficient backup system based on git
description: |
    Very efficient backup system based on the git packfile format, providing fast incremental saves and global deduplication (among and within files, including virtual machine images).
builddeps  :
    - pkgconfig(python3)
    - git
    - pandoc
    - par2cmdline
    - python-pylibacl
    - python-pytest
    - python-pyxattr
    - python-tornado
    - rsync
rundeps    :
    - git
    - par2cmdline
    - python-pyxattr
    - python-pylibacl
    - python-tornado
build      : |
    %make PYTHON=python3
install    : |
    %make_install PREFIX=%PREFIX% LIBDIR=%libdir%/bup

    # Remove docs
    rm -r $installdir/usr/share/doc
#Only run this locally. Takes forever otherwise.
#check      : |
#    rm test/ext/test-help # This test fails
#    make check
