name       : bup
version    : '0.31'
release    : 4
source     :
    - https://github.com/bup/bup/archive/0.31.tar.gz : 2f54351aed653b4b9567d3a534af598a5bc63b32efd7cc593bcecac3b89e16d1
homepage   : https://bup.github.io
license    :
    - BSD-2-Clause
    - LGPL-2.0-or-later
    - Python-2.0
component  : system.util
summary    : Efficient backup system based on git
description: |
    Very efficient backup system based on the git packfile format, providing fast incremental saves and global deduplication (among and within files, including virtual machine images).
builddeps  :
    - pkgconfig(python3)
    - git
    - par2cmdline       # check
    - python-pyxattr    # check
    - python-pylibacl   # check
    - python-tornado    # check
    - rsync             # check
rundeps    :
    - git
    - par2cmdline
    - python-pyxattr
    - python-pylibacl
    - python-tornado
build      : |
    %make PYTHON=python3
install    : |
    %make_install PREFIX=%PREFIX% LIBDIR=%libdir%/bup
check      : |
    %make check
