name       : bup
version    : 0.29.1
release    : 1
source     :
    - https://github.com/bup/bup/archive/0.29.1.tar.gz : d24b53c842d1edc907870aa69facbd45f68d778cc013b1c311b655d10d017250
license    : LGPL-2.0-or-later
component  : system.util
summary    : Efficient backup system based on git
description: |
    Very efficient backup system based on the git packfile format, providing fast incremental saves and global deduplication (among and within files, including virtual machine images).
builddeps  : 
    - git
    - python-llfuse
    - python-attrs
    - python-tornado
rundeps    : 
    - git
    - python-pyxattr
    - python-pylibacl
build      : |
    %make
install    : |
    %make_install PREFIX=%PREFIX% LIBDIR=%libdir%
